# Generated by Django 6.0.4 on 2026-05-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritequote',
            name='added_at',
        ),
    ]
