# Generated by Django 6.0.4 on 2026-05-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0002_remove_favoritequote_added_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(default='Unknown', max_length=100)),
                ('category', models.CharField(default='Motivation', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='favoritequote',
            name='category',
            field=models.CharField(default='Motivation', max_length=50),
        ),
        migrations.AlterField(
            model_name='favoritequote',
            name='author',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
